### ISSUE TITLE
Full text search endpoint isteği

### ISSUE THREAD

**Issue by mehmetkose** [acikkaynak/deprem-yardim-com#11]
Eski versiyondaki https://depremyardim.com/help/datatable üzerinden bazı kelimeleri 

Termal Kamera,Çadır,Yemek,Su,Kıyafet,İlaç,Kan,hilti,şaloma,tüp,kablo,vinç,İş Makinesi,Elektrik,Jeneratör,çocuk bezi,kadın pedi,operatör,mama,çocuk,malzeme

içerenlerini aralardan listeleyip bir sayfada topluyordum. Sahadaki Telsizci ve Offroad'cu arkadaşlara ulaştırmaya çalışıyordum. 

Yeni apide bu şekilde kullanabileceğim bir endpoint var mı? sayfayı kapatmalı mıyım?

<img width="782" alt="Screen Shot 2023-02-10 at 01 10 36" src="https://user-images.githubusercontent.com/706678/217950834-1edf1d5f-35dd-4955-ba72-b070e63985b4.png">

**Comment by aozen** [comment]
@mehmetkose istedigin endpoint
https://depremyardim.com/injured
burada. Bu adresten istedigin text search + city filter yapabilirsin.
Bu endpointe attigin istekler eger redirect edilirse veya ulasamazsan
https://depremyardim.com/yardim-isteyenler sonrasinda burayi kontrol edebilirsin. Yakin zamanda url bu sekilde degisebilir.

**Comment by mehmetkose** [comment]
Teşekkürler, yanlış anlamayın herkes iyi niyetle hareket ediyor ama bu sitenin alt yapısı neden 4 günde 3 kere değişti anlamakta zorlanıyorum 

depremyardim.com/json.php

kullandım, sonra şu oldu

https://depremyardim.com/api/list

sonra bu oldu

https://depremyardim.com/help/datatable

ve en son şuna döndü

https://depremyardim.com/injured

bu site sadece veri topluyorsa bu bir api.php ve 40kb'lık bir form ile çözülebilirdi
