### ISSUE TITLE
Refactor: Request for API key to access all data from API endpoint

### ISSUE THREAD

**Issue by TarikKaanKoc** [acikkaynak/deprem-yardim-com#16]
### Unable to retrieve data from API endpoint

I am trying to retrieve all data from the API endpoint at https://depremyardim.com, but I am unable to do so without an API key.

Could you please provide me with an API key so that I can access the data from the endpoint? I would greatly appreciate it.

Thank you in advance.

* **Discord kullanıcı adı:** @Tarık Kaan KOÇ#1949

**Comment by FurkanGM** [comment]
Contacted via Discord
