### ISSUE TITLE
bug: Şehir, ilçe, mahalle seçiminde bug

### ISSUE THREAD

**Issue by cempehlivan** [acikkaynak/deprem-yardim-com#24]
## Hata Tanımı
Şehir, ilçe, mahalle seçtikten sonra şehir veya ilçe değiştirildiğinde alt değerler sıfırlanmıyor. 

** discord kullanıcı adı: @cempehlivan#1350 **

## Beklenen Davranış
Şehir değiştirildiğinde, ilçe ve mahalle tekrardan "seçiniz" e dönmeli. İlçe değiştirildiğinde, mahalle kısmı tekrardan "seçiniz" e dönmeli.

## Ekran Görüntüleri
![1](https://user-images.githubusercontent.com/25860078/218255233-1228d44d-fc98-4fbd-a9f4-69d677c82bc1.jpg)
Hatay yerine Adana seçiyorum;
![2](https://user-images.githubusercontent.com/25860078/218255257-4c79d88d-d795-40f2-996b-64b6d8cc298c.jpg)

**Comment by FurkanGM** [comment]
Düzeltildi
