### ISSUE TITLE
feat: İhbar saat kaçta ve hangi gün yapılmış?

### ISSUE THREAD

**Issue by b-tekinli** [acikkaynak/deprem-yardim-com#29]
## İsteğiniz şeyi tanımlayın 
depremyardim.com üzerinden yapılan ihbarların saat kaçta ve hangi gün yapıldığının gösterilmesi gerektiğini düşünüyorum. aynı zamanda filtreleme yaparken de mesela son 1 saat içinde yapılmış ihbarları vs. görmek istiyorum çok işe yarıyor. arayarak ihbar yapıyorum teyit etmek için ya da ekiplerle direkt olarak iletişim kurmak için ama kaç saat önce o enkazdan ses gelmiş bu infoları veremiyorum bu yüzden çok önemli.

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: @sudosuz root#9401 **

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by FurkanGM** [comment]
https://depremyardim.com/yardim-isteyenler adresi üzerinden saat kaçta bildirildiğini görebilir ve filtreleme yapabilirsiniz
