### ISSUE TITLE
Öneri - yakinimibul.net'e bağlantı verilmesi

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardim-com#3]
Yakınlarını depremyardim.com'da bulan insanların, hastanelere sevk kayıtlarını da kontrol etmesi için
https://yakinimibul.net adresine bağlantı verilmesini öneriyorum.

Daha geniş hastane sevk kaydı olan bir web sitesi var ise ona yönlendirilmesi daha uygun olur, ben bunu buldum.

**Comment by kadirildeniz** [comment]
pr atıldı

**Comment by FurkanGM** [comment]
solved with #23
