### ISSUE TITLE
bug: Information Disclosure

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-yardim-com#30]
**Error Description**:
You can intercept and change the value of "per page" value (which is bottom of to screen) to whatever you want and receive all entered data.

Discord username: toooboring#1074

**Error Environment**:
depremyardim.com/livewire/message/injured-table 

**Describe how you got the error step by step**:

1. Go to https://depremyardim.com/
2. Click show all. 
![image](https://user-images.githubusercontent.com/124896653/218286913-5b886a78-b35a-4607-b851-5e5adca5e9fc.png)
3. Turn Intercept to on (I used burp it depends which proxy you are using)
![image](https://user-images.githubusercontent.com/124896653/218286950-0556521f-5817-4975-80c6-4e2461dcedd9.png)
4. Select a value.
![image](https://user-images.githubusercontent.com/124896653/218286970-d387244f-67f0-4869-b1f5-0c67e85136d6.png)
5. Check your request
![image](https://user-images.githubusercontent.com/124896653/218287022-5be6f0df-5976-483c-a9e7-b3adbc9f2b0a.png)
6. Send it to Repeater
![image](https://user-images.githubusercontent.com/124896653/218287047-be6c2674-f744-4fe7-ba25-13b9504b6e5c.png)
7. Scroll down until you see "value" 
![image](https://user-images.githubusercontent.com/124896653/218287290-1f1bbf34-8083-492f-ae94-aa438fda35ef.png)
8. Change value and send it.
![image](https://user-images.githubusercontent.com/124896653/218287109-818378a8-2267-488f-8cff-1baee377c724.png)
![image](https://user-images.githubusercontent.com/124896653/218287134-2c31cb0d-4767-4785-87dd-bacffb379e8f.png)

**Important Note**: If you do not think that your computer can handle such amount data, do not enter a high value, burp would crash.

**Expected Behaviour**:
There should be a limitation  in the back end.

**Operating System**: Fedora 37
Browser [Chromium]
Version [110.0.5481.77 (Official Build) (64-bit)]

**Additional Context**:
Setting the limit to 100 seems viable.

**Comment by FurkanGM** [comment]
fixed with #31
