### ISSUE TITLE
Öneri - IT Deprem Yardım Discord bağlantısının kaldırılması

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/deprem-yardim-com#4]
Web sitesini kullanan ve kullanacak olan insanlar genellikle teknolojiden ve discord gibi platformları bilmeyen insanlar. IT ekibine ulaşmak isteyen insanlar kolay bir şekilde kanalı internet üzerinden bulabilir. Acil yardıma olan insanların kafalarının karışmaması ve doğrudan ihtiacı olan bağlantılara ilerlemesi için web sitesinin tepesinde bulunan discord bağlantısı kaldırılmalı.

**Comment by Kn0ax** [comment]
IT-Deprem Yardım ekibi altındaki bütün projeler, bu discord bağlantısına sahipler. Ayrıca herhangi bir konuda proje ile iletişime geçilmesi gerektiği durumda yardımcı olacağı için kaldırılması mantıklı gelmedi.

**Comment by mehmettalhairmak** [comment]
Web sitesinde, kullanici icin geliştirici ekibe ulasmasini gerektirecek bir zaafiyet gozukmuyor su anlik. Eger gelistirici ekip tarafindan bir problem tespit edilirse bunu issue acarak bildirebilirler, issue acamayacak durumda olan vatandaslarimizin twitter uzerinden paylasmis oldugu gonderileri takip ediyoruz, bunun disinda yardim personellerimiz tarafindan ozel bir talep gelirse de avukatlarimiz bu konu ile ilgili sureki olarak kendileriyle iletisim halinde, avukatlarimizdan bize bir geribildirim gelirse de ayni sekilde gerekli kontroller saglanir. Son kullanici tarafinda ise zaten yardim personelleri-depremzedeler arasinda bire bir iletisim saglanacagi icin boyle bir seyin aksiyon alinmasina gerek duymuyorum.
