### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by tnygns** [acikkaynak/deprem-yardim-com#9]
## İsteğiniz şeyi tanımlayın 
api call ile full datayi cekmek 
format:
id	city	district	street			apartment_no	apartment_floor	phone	address	fullname	source	created_at	updated_at

-- bu bilgiyi ekleyiniz
** discord kullanıcı adı: tnygns#8415

## Değerlendirdiğiniz alternatifleri tanımlayın
Değerlendirdiğiniz herhangi bir alternatif çözüm veya özellik hakkında açık ve kısa bir açıklama.

## Ek Bağlam
Bu özellik isteği hakkında herhangi bir başka bağlam veya ekran görüntüsü ekleyin.

**Comment by FurkanGM** [comment]
Aşağıdaki endpoint #10 ile birlikte canlıya alındı. Discord üzerinden api key iletmiş olacağım

https://depremyardim.com/api/injureds?api_key=KEY
